remote_theme: pages-themes/leap-day@v0.2.0
plugins:
  - jekyll-relative-links
  - jekyll-remote-theme # add this line to the plugins list if you already have one
relative_links:
  enabled: true
  collections: true
include:
  - tools/application.md
  - tools/development.md
  - tools/model.md
  - tags/application/license.md
  - tags/application/purpose.md
  - tags/application/region.md
  - tags/development/license.md
  - tags/development/region.md
  - tags/model/license.md
  - tags/model/region.md
  

